Repository masters2023-project-03-second-hand/second-hand-max-be-a, pull requests merged in 2023-09, with the labels that each got.

#22 [feat] 프로필 사진 변경 기능
  backend/build.gradle
  backend/src/main/java/codesquard/app/api/image/ImageService.java
  backend/src/main/java/codesquard/app/api/image/ImageUploader.java
  backend/src/main/java/codesquard/app/api/member/MemberController.java
  backend/src/main/java/codesquard/app/api/member/MemberService.java
  backend/src/main/java/codesquard/app/domain/image/ImageFile.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/test/java/codesquard/app/api/item/unit/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/support/SupportRepository.java
Labels: feat

#23 [fix] CORS 필터 추가 및 로그백 추가
  backend/Dockerfile-local
  backend/docker-compose-local.yml
  backend/src/main/java/codesquard/app/config/CorsFilter.java
  backend/src/main/java/codesquard/app/config/WebConfig.java
  backend/src/main/resources/logback-spring.xml
Labels: bug

#26 [feat] 액세스 토큰 갱신 서비스 구현
  backend/Dockerfile
  backend/Dockerfile-local
  backend/docker-compose-dev.yml
  backend/docker-compose-local.yml
  backend/src/main/java/codesquard/app/api/errors/errorcode/ImageErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ItemErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/JwtTokenErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/OauthErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/exception/RestApiException.java
  backend/src/main/java/codesquard/app/api/errors/handler/GlobalExceptionHandler.java
  backend/src/main/java/codesquard/app/api/oauth/OauthRestController.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLoginRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLogoutRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthRefreshRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthAccessTokenResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLoginMemberResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLoginResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLogoutResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthRefreshResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthSignUpResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthUserProfileResponse.java
  backend/src/main/java/codesquard/app/api/response/ApiResponse.java
  backend/src/main/java/codesquard/app/config/CorsFilter.java
  backend/src/main/java/codesquard/app/config/OauthConfig.java
  backend/src/main/java/codesquard/app/config/RedisRepositoryConfig.java
  backend/src/main/java/codesquard/app/config/ValidationGroups.java
  backend/src/main/java/codesquard/app/config/ValidationSequence.java
  backend/src/main/java/codesquard/app/config/WebConfig.java
  backend/src/main/java/codesquard/app/domain/jwt/JwtProperties.java
  backend/src/main/java/codesquard/app/domain/jwt/JwtProvider.java
  backend/src/main/java/codesquard/app/domain/member/AuthenticateMember.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/java/codesquard/app/domain/member/MemberRepository.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/main/java/codesquard/app/domain/oauth/client/NaverOauthClient.java
  backend/src/main/java/codesquard/app/domain/oauth/client/OauthClient.java
  backend/src/main/java/codesquard/app/domain/oauth/properties/OauthProperties.java
  backend/src/main/java/codesquard/app/domain/oauth/support/AuthPrincipalArgumentResolver.java
  backend/src/main/java/codesquard/app/domain/oauth/support/AuthenticationContext.java
  backend/src/main/java/codesquard/app/domain/oauth/support/Principal.java
  backend/src/main/java/codesquard/app/filter/JwtAuthorizationFilter.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/domain/jwt/JwtProviderTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberRepositoryTest.java
Labels: feat

#28 [feat] 카테고리 목록 조회 및 선택 API 구현
  backend/src/main/java/codesquard/app/api/category/CategoryQueryService.java
  backend/src/main/java/codesquard/app/api/category/CategoryRestController.java
  backend/src/main/java/codesquard/app/api/category/request/CategorySelectedRequest.java
  backend/src/main/java/codesquard/app/api/category/response/CategoryItemResponse.java
  backend/src/main/java/codesquard/app/api/category/response/CategoryListResponse.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/CategoryErrorCode.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLoginRequest.java
  backend/src/main/java/codesquard/app/domain/category/Category.java
  backend/src/main/java/codesquard/app/domain/category/CategoryRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/ControllerTestSupport.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/category/CategoryFixedFactory.java
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/category/CategoryRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/domain/jwt/JwtProviderTest.java
Labels: feat

#31 [feat] 회원가입 설계 변경으로 인한 코드 수정
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/config/ValidationGroups.java
  backend/src/main/java/codesquard/app/config/ValidationSequence.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
Labels: refactor

#36 [feat] 관심상품 등록, 취소 기능
  backend/src/main/java/codesquard/app/api/errors/errorcode/ItemErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/WishErrorCode.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemController.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemService.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/java/codesquard/app/domain/wish/WishRepository.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
  backend/src/test/java/codesquard/support/DatabaseInitializer.java
Labels: feat

#37 [feat] 상품 상세 조회 API 구현
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemQueryService.java
  backend/src/main/java/codesquard/app/api/item/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/response/ItemDetailResponse.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/java/codesquard/app/domain/image/Image.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/item/ItemPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/jwt/JwtProvider.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/ControllerTestSupport.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/category/CategoryFixedFactory.java
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ImageFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/item/WishFixedFactory.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomTest.java
  backend/src/test/java/codesquard/app/domain/item/ItemTest.java
  backend/src/test/java/codesquard/app/domain/jwt/JwtProviderTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberRepositoryTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberTest.java
  backend/src/test/java/codesquard/support/DatabaseInitializer.java
Labels: feat

#40 [feat] 관심상품 목록 조회 기능
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/response/ItemResponses.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemController.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemService.java
  backend/src/main/java/codesquard/app/domain/category/Category.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/java/codesquard/app/domain/wish/WishRepository.java
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
  backend/src/test/java/codesquard/support/SupportRepository.java
Labels: feat

#41 [fix] 테스트 코드 문제 해결
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/test/java/codesquard/app/api/item/ItemQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/WishFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomTest.java
  backend/src/test/java/codesquard/app/domain/item/ItemTest.java
Labels: bug

#43 [fix] 액세스 토큰 갱신 서비스 응답 형식 변경
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthJwtResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthRefreshResponse.java
  backend/src/main/java/codesquard/app/domain/jwt/Jwt.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
Labels: bug

#46 [feat] 주소 목록 조회 API 구현
  backend/build.gradle
  backend/docker-compose-dev.yml
  backend/docker-compose-local.yml
  backend/src/main/java/codesquard/app/annotation/Addresses.java
  backend/src/main/java/codesquard/app/annotation/LoginId.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/CategoryErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ImageErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ItemErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/JwtTokenErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/OauthErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/WishErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/exception/RestApiException.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemQueryService.java
  backend/src/main/java/codesquard/app/api/item/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/response/ItemDetailResponse.java
  backend/src/main/java/codesquard/app/api/member/MemberService.java
  backend/src/main/java/codesquard/app/api/oauth/OauthRestController.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/api/region/RegionQueryService.java
  backend/src/main/java/codesquard/app/api/region/RegionRestController.java
  backend/src/main/java/codesquard/app/api/region/request/RegionListRequest.java
  backend/src/main/java/codesquard/app/api/region/response/RegionItemResponse.java
  backend/src/main/java/codesquard/app/api/region/response/RegionListResponse.java
  backend/src/main/java/codesquard/app/api/response/ItemResponses.java
  backend/src/main/java/codesquard/app/config/validation/AddressesValidator.java
  backend/src/main/java/codesquard/app/config/validation/LoginIdValidator.java
  backend/src/main/java/codesquard/app/domain/category/Category.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/image/Image.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/java/codesquard/app/domain/region/Region.java
  backend/src/main/java/codesquard/app/domain/region/RegionPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/region/RegionRepository.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/main/resources/regions.csv
  backend/src/test/java/codesquard/app/ControllerTestSupport.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/WishFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/region/RegionQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/region/RegionRestControllerTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomTest.java
  backend/src/test/java/codesquard/app/domain/item/ItemTest.java
  backend/src/test/java/codesquard/app/domain/region/RegionFixedFactory.java
  backend/src/test/java/codesquard/app/domain/region/RegionPaginationRepositoryTest.java
Labels: feat

#48 [refactor] 로그아웃 서비스 기능 리팩토링
  backend/src/main/java/codesquard/app/api/oauth/OauthRestController.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLogoutRequest.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLogoutResponse.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemService.java
  backend/src/main/java/codesquard/app/config/WebConfig.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/java/codesquard/app/filter/JwtAuthorizationFilter.java
  backend/src/main/java/codesquard/app/interceptor/LogoutInterceptor.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
Labels: refactor

#57 [bug] 로그인 요구 인가 필터에 제외할 경로 추가
  backend/src/main/java/codesquard/app/api/oauth/OauthRestController.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/filter/JwtAuthorizationFilter.java
Labels: bug

#60 [feat] 회원 동네 삭제 기능 구현
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberTownErrorCode.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownRestController.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownValidator.java
  backend/src/main/java/codesquard/app/api/membertown/request/MemberTownAddRequest.java
  backend/src/main/java/codesquard/app/api/membertown/request/MemberTownRemoveRequest.java
  backend/src/main/java/codesquard/app/api/membertown/response/MemberTownRemoveResponse.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
Labels: feat

#62 [refactor] 일대다 양방향 관계를 다대일 단방향 관계로 리팩토링
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberTownErrorCode.java
  backend/src/main/java/codesquard/app/api/item/ItemQueryService.java
  backend/src/main/java/codesquard/app/api/item/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/response/ItemDetailResponse.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownValidator.java
  backend/src/main/java/codesquard/app/api/membertown/response/MemberTownRemoveResponse.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemService.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/java/codesquard/app/domain/image/Image.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTownRepository.java
  backend/src/main/java/codesquard/app/domain/wish/Wish.java
  backend/src/main/java/codesquard/app/domain/wish/WishRepository.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/item/ImageFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/WishFixedFactory.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatLogTest.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomFixedFactory.java
  backend/src/test/java/codesquard/app/domain/chat/ChatRoomTest.java
  backend/src/test/java/codesquard/app/domain/item/ItemTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberTest.java
Labels: refactor

#64 [refactor] 회원가입 입력 형식 변경
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberErrorCode.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/config/validation/AddressesValidator.java
  backend/src/main/java/codesquard/app/domain/region/RegionRepository.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
Labels: refactor

#65 [feat] 판매 내역 조회
  backend/src/main/java/codesquard/app/api/converter/SalesRequestConverter.java
  backend/src/main/java/codesquard/app/api/converter/WishRequestConverter.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/SalesErrorCode.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/sales/SalesItemController.java
  backend/src/main/java/codesquard/app/api/sales/SalesItemService.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemService.java
  backend/src/main/java/codesquard/app/config/WebConfig.java
  backend/src/main/java/codesquard/app/domain/pagination/PaginationUtils.java
  backend/src/main/java/codesquard/app/domain/sales/SalesPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/sales/SalesStatus.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/sales/SalesItemServiceTest.java
Labels: feat

#69 [refactor] 회원 동네 추가/삭제 입력 형식 변경 및 로그인 응답 결과 변경
  backend/src/main/java/codesquard/app/api/errors/errorcode/OauthErrorCode.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownValidator.java
  backend/src/main/java/codesquard/app/api/membertown/request/MemberTownAddRequest.java
  backend/src/main/java/codesquard/app/api/membertown/request/MemberTownRemoveRequest.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/response/MemberTownLoginResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLoginMemberResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthRefreshResponse.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTownRepository.java
  backend/src/main/java/codesquard/app/domain/region/Region.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
Labels: refactor

#70 [feat] 상품 수정 서비스 구현
  backend/src/main/java/codesquard/app/api/category/request/CategorySelectedRequest.java
  backend/src/main/java/codesquard/app/api/category/response/CategoryItemResponse.java
  backend/src/main/java/codesquard/app/api/category/response/CategoryListResponse.java
  backend/src/main/java/codesquard/app/api/converter/ItemRequestConverter.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ImageErrorCode.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ItemErrorCode.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/ItemValidator.java
  backend/src/main/java/codesquard/app/api/item/request/ItemModifyRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLoginRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthLogoutRequest.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthRefreshRequest.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthAccessTokenResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthJwtResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLoginResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthLogoutResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthSignUpResponse.java
  backend/src/main/java/codesquard/app/api/oauth/response/OauthUserProfileResponse.java
  backend/src/main/java/codesquard/app/api/region/request/RegionListRequest.java
  backend/src/main/java/codesquard/app/api/region/response/RegionItemResponse.java
  backend/src/main/java/codesquard/app/domain/image/Image.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/api/item/ImageFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/resources/roller_blade.jpeg
Labels: feat

#72 [feat] 상품 상태 수정 기능 구현
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/request/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/item/request/ItemStatusModifyRequest.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/item/ItemStatus.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/sales/SalesItemServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
Labels: feat

#80 [refactor] : 프로필 이미지 응답 값 수정
  backend/src/main/java/codesquard/app/api/member/MemberController.java
  backend/src/main/java/codesquard/app/api/member/MemberService.java
  backend/src/main/java/codesquard/app/api/member/response/MemberProfileResponse.java
Labels: refactor

#81 [refactor] 4주차 피드백 반영 - 2
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/request/OauthSignUpRequest.java
  backend/src/main/java/codesquard/app/api/redis/RedisService.java
  backend/src/main/java/codesquard/app/domain/category/Category.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/jwt/Jwt.java
  backend/src/main/java/codesquard/app/domain/jwt/JwtProvider.java
  backend/src/main/java/codesquard/app/domain/member/Member.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/main/java/codesquard/app/domain/region/Region.java
  backend/src/test/java/codesquard/app/CategoryTestSupport.java
  backend/src/test/java/codesquard/app/ControllerTestSupport.java
  backend/src/test/java/codesquard/app/ImageTestSupport.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/MemberTestSupport.java
  backend/src/test/java/codesquard/app/RegionTestSupport.java
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/category/CategoryRestControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ImageFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemFixedFactory.java
  backend/src/test/java/codesquard/app/api/item/ItemQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthFixedFactory.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/properties/OauthPropertiesTest.java
  backend/src/test/java/codesquard/app/api/region/RegionQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/region/RegionRestControllerTest.java
  backend/src/test/java/codesquard/app/api/sales/SalesItemServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
  backend/src/test/java/codesquard/app/domain/jwt/JwtProviderTest.java
  backend/src/test/java/codesquard/app/domain/member/AuthenticateMemberTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberRepositoryTest.java
  backend/src/test/java/codesquard/app/domain/oauth/InMemoryOauthClientRepositoryTest.java
  backend/src/test/java/codesquard/app/domain/region/RegionFixedFactory.java
  backend/src/test/java/codesquard/app/domain/region/RegionPaginationRepositoryTest.java
Labels: refactor

#86 [refactor] 상품 게시글 수정시 썸네일 로직 개선
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/request/ItemModifyRequest.java
  backend/src/main/java/codesquard/app/domain/category/Category.java
  backend/src/main/java/codesquard/app/domain/image/Image.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/category/CategoryRestControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/member/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/member/unit/MemberServiceTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/properties/OauthPropertiesTest.java
  backend/src/test/java/codesquard/app/api/region/RegionQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/region/RegionRestControllerTest.java
  backend/src/test/java/codesquard/app/api/sales/SalesItemServiceTest.java
  backend/src/test/java/codesquard/app/api/wishitem/WishItemServiceTest.java
  backend/src/test/java/codesquard/app/domain/jwt/JwtProviderTest.java
  backend/src/test/java/codesquard/app/domain/member/AuthenticateMemberTest.java
  backend/src/test/java/codesquard/app/domain/member/MemberRepositoryTest.java
  backend/src/test/java/codesquard/app/domain/oauth/InMemoryOauthClientRepositoryTest.java
  backend/src/test/java/codesquard/app/domain/region/RegionPaginationRepositoryTest.java
Labels: feat, refactor

#91 [feat] 제품 상세 조회 시 viewCount 증가
  backend/build.gradle
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/redis/RedisService.java
  backend/src/main/java/codesquard/app/config/ScheduleConfig.java
  backend/src/main/java/codesquard/app/domain/item/ItemRepository.java
  backend/src/test/java/codesquard/app/CacheTestSupport.java
  backend/src/test/java/codesquard/app/api/redis/RedisServiceTest.java
Labels: feat

#89 [feat] 상품 삭제 서비스 구현
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
Labels: feat

#88 [feat] 회원의 동네 선택 API 구현
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberTownErrorCode.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownRestController.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/region/RegionRestController.java
  backend/src/main/java/codesquard/app/api/region/RegionService.java
  backend/src/main/java/codesquard/app/api/region/request/RegionSelectionRequest.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTownRepository.java
  backend/src/main/java/codesquard/app/domain/region/RegionRepository.java
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/MemberTownTestSupport.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/region/RegionRestControllerTest.java
  backend/src/test/java/codesquard/app/api/region/RegionServiceTest.java
Labels: feat

#87 [refactor] 로그인 응답에 isSelected 추가
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberTownErrorCode.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownRestController.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/oauth/response/MemberTownLoginResponse.java
  backend/src/main/java/codesquard/app/api/region/RegionRestController.java
  backend/src/main/java/codesquard/app/api/region/RegionService.java
  backend/src/main/java/codesquard/app/api/region/request/RegionSelectionRequest.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/java/codesquard/app/domain/image/ImageRepository.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTownRepository.java
  backend/src/main/java/codesquard/app/domain/region/RegionRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/IntegrationTestSupport.java
  backend/src/test/java/codesquard/app/MemberTownTestSupport.java
  backend/src/test/java/codesquard/app/api/item/ItemControllerTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownRestControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/api/region/RegionRestControllerTest.java
  backend/src/test/java/codesquard/app/api/region/RegionServiceTest.java
Labels: refactor

#93 [feat] 채팅방 생성 API 구현
  backend/src/main/java/codesquard/app/api/chat/ChatLogRestController.java
  backend/src/main/java/codesquard/app/api/chat/ChatLogService.java
  backend/src/main/java/codesquard/app/api/chat/ChatRoomRestController.java
  backend/src/main/java/codesquard/app/api/chat/ChatRoomService.java
  backend/src/main/java/codesquard/app/api/chat/request/ChatLogSendRequest.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogSendResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatRoomCreateResponse.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ChatRoomErrorCode.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/oauth/support/Principal.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/api/chat/ChatLogRestControllerTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatLogServiceTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatRoomRestControllerTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatRoomServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/redis/RedisServiceTest.java
Labels: feat

#99 [feat] 상품 등록 수정
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
Labels: refactor

#100 [refator] 상품 등록 썸네일 수정2
  backend/src/main/java/codesquard/app/api/item/ItemController.java
Labels: refactor

#108 [fix] 상품 목록 조회시 tradingRegion, status 응답형식 변경
  backend/docker-compose-local.yml
  backend/src/main/java/codesquard/app/domain/item/ItemPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/item/ItemStatus.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/main/resources/regions.csv
Labels: bug

#112 [fix] 썸네일 저장 문제 해결
  backend/src/main/java/codesquard/app/api/item/ItemService.java
Labels: bug

#113 [feat] 채팅 목록 조회 API 구현
  backend/docker-compose-local.yml
  backend/src/main/java/codesquard/app/annotation/MessageIndex.java
  backend/src/main/java/codesquard/app/api/chat/ChatLogRestController.java
  backend/src/main/java/codesquard/app/api/chat/ChatLogService.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogItemResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogListResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogMessageResponse.java
  backend/src/main/java/codesquard/app/api/errors/handler/GlobalExceptionHandler.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/config/validation/MessageIndexValidator.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogRepository.java
  backend/src/main/java/codesquard/app/domain/item/ItemPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/item/ItemStatus.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/main/resources/regions.csv
  backend/src/test/java/codesquard/app/api/chat/ChatLogRestControllerTest.java
Labels: feat

#110 [feat] 5주차 리뷰사항 개선
  backend/src/main/java/codesquard/app/annotation/MessageIndex.java
  backend/src/main/java/codesquard/app/api/chat/ChatLogRestController.java
  backend/src/main/java/codesquard/app/api/chat/ChatLogService.java
  backend/src/main/java/codesquard/app/api/chat/ChatRoomService.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogItemResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogListResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogMessageResponse.java
  backend/src/main/java/codesquard/app/api/errors/handler/GlobalExceptionHandler.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/ItemService.java
  backend/src/main/java/codesquard/app/api/item/request/ItemModifyRequest.java
  backend/src/main/java/codesquard/app/api/item/request/ItemRegisterRequest.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/oauth/OauthService.java
  backend/src/main/java/codesquard/app/api/redis/ItemViewRedisService.java
  backend/src/main/java/codesquard/app/api/redis/OauthRedisService.java
  backend/src/main/java/codesquard/app/api/redis/RedisService.java
  backend/src/main/java/codesquard/app/config/RedisRepositoryConfig.java
  backend/src/main/java/codesquard/app/config/WebConfig.java
  backend/src/main/java/codesquard/app/config/validation/MessageIndexValidator.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/image/ImageFile.java
  backend/src/main/java/codesquard/app/domain/item/Item.java
  backend/src/main/java/codesquard/app/domain/item/ItemRepository.java
  backend/src/main/java/codesquard/app/domain/jwt/Jwt.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTownRepository.java
  backend/src/main/java/codesquard/app/domain/oauth/client/OauthClient.java
  backend/src/main/java/codesquard/app/domain/oauth/support/Principal.java
  backend/src/main/java/codesquard/app/filter/JwtAuthorizationFilter.java
  backend/src/main/java/codesquard/app/filter/LogoutFilter.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/ControllerTestSupport.java
  backend/src/test/java/codesquard/app/ImageTestSupport.java
  backend/src/test/java/codesquard/app/MemberTestSupport.java
  backend/src/test/java/codesquard/app/api/category/CategoryQueryServiceTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatLogRestControllerTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatLogServiceTest.java
  backend/src/test/java/codesquard/app/api/item/ItemServiceTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthRestControllerTest.java
  backend/src/test/java/codesquard/app/api/oauth/OauthServiceTest.java
  backend/src/test/java/codesquard/app/api/redis/ItemViewRedisServiceTest.java
Labels: feat

#116 [feat] 채팅방 목록 조회 기능 구현
  backend/src/main/java/codesquard/app/api/chat/ChatLogService.java
  backend/src/main/java/codesquard/app/api/chat/ChatRoomRestController.java
  backend/src/main/java/codesquard/app/api/chat/ChatRoomService.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatRoomItemResponse.java
  backend/src/main/java/codesquard/app/api/chat/response/ChatRoomListResponse.java
  backend/src/main/java/codesquard/app/api/errors/errorcode/ChatLogErrorCode.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLog.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogCountRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatLogRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoom.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomPaginationRepository.java
  backend/src/main/java/codesquard/app/domain/chat/ChatRoomRepository.java
  backend/src/main/resources/db/mysql/data.sql
  backend/src/test/java/codesquard/app/api/chat/ChatLogRestControllerTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatRoomRestControllerTest.java
  backend/src/test/java/codesquard/app/api/chat/ChatRoomServiceTest.java
  backend/src/test/java/codesquard/app/domain/region/RegionSliceRepositoryTest.java
Labels: feat

#121 [feat] @JsonProperty 제거 및 오타 수정
  backend/src/main/java/codesquard/app/api/chat/response/ChatLogMessageResponse.java
  backend/src/main/java/codesquard/app/api/item/ItemController.java
  backend/src/main/java/codesquard/app/api/item/response/ItemDetailResponse.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/oauth/response/MemberTownLoginResponse.java
  backend/src/main/java/codesquard/app/api/wishitem/WishItemController.java
  backend/src/main/resources/application.yml
Labels: bug

#122 [feat] 회원 동네 삭제시 남은 동네 selected 처리
  backend/src/main/java/codesquard/app/api/errors/errorcode/MemberTownErrorCode.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/domain/membertown/MemberTown.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
Labels: feat

#123 [feat] 회원 동네 목록 조회 구현
  backend/src/main/java/codesquard/app/api/member/MemberController.java
  backend/src/main/java/codesquard/app/api/membertown/MemberTownService.java
  backend/src/main/java/codesquard/app/api/membertown/response/MemberTownItemResponse.java
  backend/src/main/java/codesquard/app/api/membertown/response/MemberTownListResponse.java
  backend/src/test/java/codesquard/app/api/member/MemberControllerTest.java
  backend/src/test/java/codesquard/app/api/membertown/MemberTownServiceTest.java
Labels: feat
